### ISSUE TITLE
Can't use on server (amazon ec2)

### ISSUE THREAD

**Issue by ssymbol** [arusanov/avatar-generator#4]
I was trying to use your library in ec2 amazon server, but having some issues, I have a suspect that this library might be related to that, any ideas?

Trace on requesting an image:

events.js:72
throw er; // Unhandled 'error' event
^
Error: spawn ENOENT
at errnoException (child_process.js:1011:11)
at Process.ChildProcess._handle.onexit (child_process.js:802:34)

I am pretty sure it is becase of it, since I am trying to fetch image and it fails...
Any folder permissions or libraries on OS?

**Comment by ssymbol** [comment]
I figured that the bug is related to the fact that ImageMagick should be installed and 'convert' should be accessible from terminal ($PATH) or give it with options.
