### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by fjeddy** [arusanov/avatar-generator#7]
Is this broken? No matter what i do i just get

```
events.js:141`
      throw er; // Unhandled 'error' event
      ^

Error: spawn convert ENOENT
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

Running all the example files directly gives the same error. Using node 4 or node 6. Using my server or Heroku!

**Comment by fjeddy** [comment]
Was missing Imagemagick on the system! Wasted a couple of hours because this isn't mentioned anywhere. Thanks.
